/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.ui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import javax.swing.JTextField;
import main.java.logic.ControladorReservas;
import main.java.logic.Reservacion;

/**
 *
 * @author Hp
 */
    public class VentanaCancelacion extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaCancelacion.class.getName());

    private ControladorReservas controlador;
    private JButton btnBuscar;
    private JButton btnCancelar;
    private JTextField txtIdReserva;
    private JTextArea txtResultado;
    /**
     * Creates new form VentanaCancelacion
     */
    public VentanaCancelacion(ControladorReservas controlador) {
        this.controlador = controlador;
        
        setTitle("Cancelar la reservacion");
        setSize(450, 350);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
        
        initComponents();
        inicializarComponentes();
        eventos();
    }
    
    private void inicializarComponentes(){
        
      setLayout(null);
      
      JLabel lblTitulo = new JLabel("Cancelar Reservacion");
      lblTitulo.setFont(new Font("Arial", Font.BOLD, 20));
      lblTitulo.setBounds(110, 10, 300, 30);
      add(lblTitulo);  
        
      JLabel lblId = new JLabel("ID de la reservacion");
      lblId.setBounds(20, 60, 200, 25);
      add(lblId);
       
      txtIdReserva = new JTextField();
      txtIdReserva.setBounds(240, 85, 150, 25);
      add(txtIdReserva);
      
      btnBuscar = new JButton("Buscar");
      btnBuscar.setBounds(240, 85, 150, 25);
      add(btnBuscar);
     
      txtResultado = new JTextArea();
      txtResultado.setEditable(false);
      JScrollPane scroll = new JScrollPane(txtResultado);
      scroll.setBounds(20, 130, 370, 120);
      add(scroll);
      
      btnCancelar = new JButton("Cancelar Reserva");
      btnCancelar.setBounds(120, 260, 200, 35);
      add(btnCancelar);
    }
    
    private void eventos(){
     
     btnBuscar.addActionListener(new ActionListener(){
         @Override
         public void actionPerformed(ActionEvent e){
             
            String id = txtIdReserva.getText().trim();
            
            if(id.isBlank()){
                JOptionPane.showMessageDialog(null, "Debe ingresar un ID valido");
                return;
            }
            
            Reservacion r = controlador.buscarReservacion(id);
            if(r == null){
                txtResultado.setText("No se encontro la reservacion");
            }else{
                txtResultado.setText(
                   "ID: " + r.getIdReservacion() + "\n" +
                   "Vuelo: " + r.getCodigoVuelo() + "\n" +
                   "Pasajero: " + r.getPasajero().getNombre() + "\n" +
                   "Asiento: " + String.join(", ", r.getIdAsiento()) + "\n"
                );
            }
         }
     });   
     
     
  

      btnCancelar.addActionListener(new ActionListener(){
        
        @Override
        public void actionPerformed(ActionEvent e){

         String id = txtIdReserva.getText().trim();

       if(id.isBlank()){

        JOptionPane.showMessageDialog(null, "Debe Ingresar un ID");
        return;
       }
      
       try{
       controlador.cancelarReservacion(id);
         JOptionPane.showMessageDialog(null, "La reservacion fue cancelada");
         txtResultado.setText("");
       }catch(Exception ex){
           JOptionPane.showMessageDialog(null, ex.getMessage());
       }
      }
    });


   }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}  
