/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package main.java.ui;

import java.awt.Font;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.List;
import javax.swing.JComboBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JScrollPane;
import javax.swing.JTextArea;
import main.java.logic.ControladorReservas;
import main.java.logic.Reservacion;

/**
 *
 * @author Hp
 */
public class VentanaFactura extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VentanaFactura.class.getName());

    private ControladorReservas controlador;
    private JComboBox<String> comboReservas;
    private JTextArea detalleFactura;
    /**
     * Creates new form VentanaFactura
     */
    public VentanaFactura(ControladorReservas controlador) {
        this.controlador = controlador;
        
        setTitle("Facturas");
        setSize(500, 400);
        setLocationRelativeTo(null);
        setResizable(false);
        setDefaultCloseOperation(JFrame.DISPOSE_ON_CLOSE);
                
        initComponents();
        
        setLayout(null);
        inicializarComponentes();
        cargaReservas();
        eventos();
    }

    private void inicializarComponentes(){
        
       setLayout(null);
       
       JLabel lblTitulo = new JLabel("Facturas creadas");
       lblTitulo.setFont(new Font("Arial", Font.BOLD, 20));
       lblTitulo.setBounds(150, 10, 300, 30);
       add(lblTitulo);
       
       JLabel lblReserva = new JLabel("Seleccione la reservacion");
       lblReserva.setBounds(20, 60, 200, 25);
       add(lblReserva);
       
       comboReservas = new JComboBox<>();
       comboReservas.setBounds(20, 85, 440, 25);
       add(comboReservas); 
       
       detalleFactura = new JTextArea();
       detalleFactura.setEditable(false);
       JScrollPane scroll = new JScrollPane(detalleFactura);
       scroll.setBounds(20, 130, 440, 200);
       add(scroll);
    }
    
    private void cargaReservas(){
        
      comboReservas.removeAllItems();
      
      List<Reservacion> reservas = controlador.listarReservaciones();
     
      for(Reservacion r : reservas){
          comboReservas.addItem(r.getIdReservacion());
      }        
    }
    
  private void eventos(){
   comboReservas.addActionListener(new ActionListener(){
   
           @Override
           public void actionPerformed(ActionEvent e){

            String id = (String) comboReservas.getSelectedItem();
        
           if(id == null)return;

      Reservacion r = controlador.buscarReservacion(id);

      detalleFactura.setText(
                             "Factura de reservacion\n\n" +
                             "ID Reserva: " + r.getIdReservacion() + "\n" +
                             "Vuelo: " + r.getCodigoVuelo() + "\n" +
                             "Pasajero: " + r.getPasajero().getNombre() + "\n" +
                             "Cedula: " +r.getPasajero().getCedula() + "\n" +
                             "Telefono: " + r.getPasajero().getTelefono() + "\n" +
                             "Asiento: " + String.join(", ", r.getIdAsiento()) + "\n" +
                             "Fecha: " + r.getFechaCreacion().toString() + "\n" +
                             "\nTotal: " + calcularMonto(r)

                );
           }
});
   
}   
    private int calcularMonto(Reservacion r){
        return r.getIdAsiento().length * 45000;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
